app_name: StreamingLogProcessor
time_batch_window: 5
max_size_window: 100
kafka:
  brokers: localhost:9092
  topic: test
influx:
  host: localhost
  port: 8086
  user: superadmin
  pass: eskere
  db: tmp
  input_fields:
